version: '3.7'

services:

  ldap-host:
    image: osixia/openldap:1.2.4
    container_name: ldap-host
    hostname: ldap-service
    environment:
      - LDAP_ORGANISATION="MyCompany Inc."
      - LDAP_DOMAIN=mycompany.com
    ports:
      - "389:389"

  phpldapadmin-service:
    image: osixia/phpldapadmin:0.7.2
    container_name: phpldapadmin-service
    hostname: phpldapadmin-service
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap-host
    ports:
      - "6443:443"
    depends_on:
      - ldap-host