version: '3.5'
services:

  ldap-service:
    image: osixia/openldap:1.2.1
    container_name: ldap-service
    hostname: ldap-service
    environment:
      - LDAP_ORGANISATION="MyCompany Inc."
      - LDAP_DOMAIN=mycompany.com
    ports:
      - 389:389
#    healthcheck:
#      test: ???
#      start_period: 10s

  phpldapadmin-service:
    image: osixia/phpldapadmin:0.7.1
    container_name: phpldapadmin-service
    hostname: phpldapadmin-service
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap-host
    ports:
      - 6443:443
    depends_on:
      - ldap-service
    links:
      - ldap-service:ldap-host
#    healthcheck:
#      test: ???
#      start_period: 10s